name: club_location_first_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  provider: ^6.1.5
  json_annotation: ^4.8.1
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  font_awesome_flutter: ^10.8.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  geolocator_android: 4.3.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

